/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cypherstudios.booking.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Victor
 */
public class BookingList extends javax.swing.JDialog {

    //Variable para la img de background del JPanel lateral
    BookingList.BackgroundPanel bg = new BookingList.BackgroundPanel();

    //Colores
    private Color colRed = new Color(255, 0, 0);
    private Color colBlack = new Color(0, 0, 0);
    private Color colWhite = new Color(255, 255, 255);

    /**
     * Creates new form BookingList
     */
    public BookingList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        panelBackground = new BackgroundPanel();
        nameBooking = new javax.swing.JLabel();
        nameEvent = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        formDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBookingList = new javax.swing.JTable();
        btnBookingList = new javax.swing.JButton();
        navBar = new javax.swing.JMenuBar();
        navItemFile = new javax.swing.JMenu();
        navItemReturn = new javax.swing.JMenuItem();
        navItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnReturn.setBackground(new java.awt.Color(0, 0, 0));
        btnReturn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnReturn.setForeground(nameEvent.getForeground());
        btnReturn.setText("Volver");
        btnReturn.setToolTipText("Vuelve a la ventana anterior");
        btnReturn.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 30, 7, 30));
        btnReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        panelBackground.setBackground(new java.awt.Color(44, 44, 44));
        panelBackground.setForeground(new java.awt.Color(255, 255, 255));
        panelBackground.setMaximumSize(new java.awt.Dimension(800, 500));
        panelBackground.setMinimumSize(new java.awt.Dimension(800, 500));
        panelBackground.setPreferredSize(new java.awt.Dimension(250, 460));
        panelBackground.setRequestFocusEnabled(false);
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameBooking.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        nameBooking.setForeground(new java.awt.Color(160, 0, 0));
        nameBooking.setText("BOOKING");
        panelBackground.add(nameBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        nameEvent.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        nameEvent.setForeground(new java.awt.Color(255, 0, 0));
        nameEvent.setText("EVENTS");
        panelBackground.add(nameEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cypherstudios/booking/resources/logo-circle-100x100.png"))); // NOI18N
        imgLogo.setToolTipText("");
        panelBackground.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 100));

        formDesc.setFont(getFont());
        formDesc.setForeground(panelBackground.getForeground());
        formDesc.setText("<html><p style=\\\"width:80%\\\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sapien neque, sodales vehicula faucibus in</p></html>");
        formDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelBackground.add(formDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 140));

        jtBookingList.setFont(getFont());
        jtBookingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jtBookingList);

        btnBookingList.setBackground(new java.awt.Color(0, 0, 0));
        btnBookingList.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnBookingList.setForeground(nameEvent.getForeground());
        btnBookingList.setText("Ver reservas");
        btnBookingList.setToolTipText("Vuelve a la ventana anterior");
        btnBookingList.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 20, 7, 20));
        btnBookingList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBookingList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBookingList.setPreferredSize(new java.awt.Dimension(120, 20));
        btnBookingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingListActionPerformed(evt);
            }
        });

        navBar.setBackground(panelBackground.getBackground());
        navBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        navBar.setForeground(panelBackground.getForeground());
        navBar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        navBar.setPreferredSize(new java.awt.Dimension(51, 40));

        navItemFile.setBackground(navBar.getBackground());
        navItemFile.setBorder(navBar.getBorder());
        navItemFile.setForeground(navBar.getForeground());
        navItemFile.setText("Archivo");
        navItemFile.setToolTipText("");
        navItemFile.setFont(navBar.getFont());

        navItemReturn.setBackground(navBar.getBackground());
        navItemReturn.setFont(navItemFile.getFont());
        navItemReturn.setForeground(navBar.getForeground());
        navItemReturn.setText("Volver");
        navItemReturn.setToolTipText("");
        navItemReturn.setPreferredSize(new java.awt.Dimension(200, 30));
        navItemFile.add(navItemReturn);

        navItemExit.setBackground(navBar.getBackground());
        navItemExit.setFont(navItemFile.getFont());
        navItemExit.setForeground(navBar.getForeground());
        navItemExit.setText("Salir");
        navItemExit.setPreferredSize(new java.awt.Dimension(200, 30));
        navItemFile.add(navItemExit);

        navBar.add(navItemFile);

        setJMenuBar(navBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReturn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBookingList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBookingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReturn)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnBookingList.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnBookingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingListActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                BookingList dialog = new BookingList(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBookingList;
    public javax.swing.JButton btnReturn;
    private javax.swing.JLabel formDesc;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtBookingList;
    private javax.swing.JLabel nameBooking;
    private javax.swing.JLabel nameEvent;
    public javax.swing.JMenuBar navBar;
    public javax.swing.JMenuItem navItemExit;
    public javax.swing.JMenu navItemFile;
    public javax.swing.JMenuItem navItemReturn;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables


    /* Métodos Hover */
    private void btnHoverOn(javax.swing.JButton btn) {
        btn.setBackground(colRed);
        btn.setForeground(colBlack);
    }

    private void btnHoverOut(javax.swing.JButton btn) {
        btn.setBackground(colBlack);
        btn.setForeground(colWhite);
    }

    /* Clase interna para poner img background al JPanel*/
    class BackgroundPanel extends JPanel {

        private Image imgBg;

        @Override
        public void paint(Graphics g) {
            imgBg = new ImageIcon(getClass().getResource("../resources/img-bg-left-dark.jpg")).getImage();
            g.drawImage(imgBg, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
