/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cypherstudios.booking.view;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Victor
 */
public class AppInit extends javax.swing.JFrame {

    //Variables para el falso boton X cerrar
    int xMouse, yMouse;

    //Variable para la img de background del JPanel lateral
    BackgroundPanel bg = new BackgroundPanel();

    //Colores
    private Color colRed = new Color(255, 0, 0);
    private Color colBlack = new Color(0, 0, 0);
    private Color colWhite = new Color(255, 255, 255);

    /**
     * Creates new form appIni
     */
    public AppInit() {
        //Llama al método para establecer la imagen de fondo para el JPane
        //this.setContentPane(bg);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new BackgroundPanel();
        btnBookingList = new javax.swing.JButton();
        nameBooking = new javax.swing.JLabel();
        nameEvent = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        btnBooking = new javax.swing.JButton();
        formTittle = new javax.swing.JLabel();
        formDesc = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(44, 44, 44));
        panelBackground.setMaximumSize(new java.awt.Dimension(800, 500));
        panelBackground.setMinimumSize(new java.awt.Dimension(800, 500));
        panelBackground.setPreferredSize(new java.awt.Dimension(250, 500));
        panelBackground.setRequestFocusEnabled(false);
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBookingList.setBackground(new java.awt.Color(0, 0, 0));
        btnBookingList.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBookingList.setForeground(new java.awt.Color(255, 255, 255));
        btnBookingList.setText("Ver Eventos");
        btnBookingList.setToolTipText("Ver Eventos");
        btnBookingList.setAutoscrolls(true);
        btnBookingList.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 30, 7, 30));
        btnBookingList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBookingList.setPreferredSize(new java.awt.Dimension(250, 50));
        btnBookingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookingListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingListMouseExited(evt);
            }
        });
        btnBookingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingListActionPerformed(evt);
            }
        });
        panelBackground.add(btnBookingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 250, -1));

        nameBooking.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        nameBooking.setForeground(new java.awt.Color(160, 0, 0));
        nameBooking.setText("BOOKING");
        panelBackground.add(nameBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        nameEvent.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        nameEvent.setForeground(new java.awt.Color(255, 0, 0));
        nameEvent.setText("EVENTS");
        panelBackground.add(nameEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 160, -1, -1));

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cypherstudios/booking/resources/logo-circle-100x100.png"))); // NOI18N
        imgLogo.setToolTipText("");
        panelBackground.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 100));

        btnBooking.setBackground(new java.awt.Color(0, 0, 0));
        btnBooking.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(255, 255, 255));
        btnBooking.setText("Reservar Evento");
        btnBooking.setToolTipText("Reservar Evento");
        btnBooking.setAutoscrolls(true);
        btnBooking.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 30, 7, 30));
        btnBooking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBooking.setPreferredSize(new java.awt.Dimension(250, 50));
        btnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingMouseExited(evt);
            }
        });
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });
        panelBackground.add(btnBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, -1));

        formTittle.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        formTittle.setText("ORGANIZA TU EVENTO");

        formDesc.setFont(getFont());
        formDesc.setText("<html><p style=\\\"width:100%\\\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sapien neque, sodales vehicula faucibus in, porta eu mauris. In nec mollis nunc, vitae euismod libero. Morbi elementum urna neque, ut porttitor risus aliquam at. Donec venenatis nunc sed condimentum aliquet. Mauris est risus, consequat id urna eu, iaculis hendrerit ipsum. Nulla non massa vel felis pretium euismod sit amet sed libero.</p></html>");
        formDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnExit.setForeground(nameEvent.getForeground());
        btnExit.setText("SALIR");
        btnExit.setToolTipText("Cierra la aplicación");
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 30, 7, 30));
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        pnlHeader.setPreferredSize(new java.awt.Dimension(40, 40));
        pnlHeader.setRequestFocusEnabled(false);
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitTxt.setBackground(getBackground());
        exitTxt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        exitTxt.setForeground(nameEvent.getForeground());
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setToolTipText("Cerrar");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.setRequestFocusEnabled(false);
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });
        pnlHeader.add(exitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(formTittle)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit)))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(formTittle)
                .addGap(18, 18, 18)
                .addComponent(formDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(25, 25, 25))
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * Captura la posición del mouse en la pantalla
     *
     * @param evt
     */
    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed

    /**
     * Hace que se pueda arrastrar la ventana con el mouse
     *
     * @param evt
     */
    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        //Capturamos las posicion del mouse en la pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        //Posiciona la ventana en las coordenadas del mouse
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitTxt.setBackground(colRed);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        //exitTxt.setBackground(new Color(60,63,65));
        exitTxt.setBackground(getBackground());
        exitTxt.setForeground(nameEvent.getForeground());
    }//GEN-LAST:event_exitTxtMouseExited

    private void btnBookingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingListActionPerformed

    private void btnBookingListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingListMouseClicked

        btnBookingList.setForeground(colRed);

    }//GEN-LAST:event_btnBookingListMouseClicked

    private void btnBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingMouseClicked

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseEntered
        btnHoverOn(this.btnBooking);
    }//GEN-LAST:event_btnBookingMouseEntered

    private void btnBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseExited
        btnHoverOut(this.btnBooking);
    }//GEN-LAST:event_btnBookingMouseExited

    private void btnBookingListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingListMouseEntered
        btnHoverOn(this.btnBookingList);
    }//GEN-LAST:event_btnBookingListMouseEntered

    private void btnBookingListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingListMouseExited
        btnHoverOut(this.btnBookingList);
    }//GEN-LAST:event_btnBookingListMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnHoverOn(this.btnExit);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnHoverOut(this.btnExit);
    }//GEN-LAST:event_btnExitMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AppInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AppInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AppInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AppInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AppInit().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBooking;
    public javax.swing.JButton btnBookingList;
    public javax.swing.JButton btnExit;
    public javax.swing.JLabel exitTxt;
    private javax.swing.JLabel formDesc;
    private javax.swing.JLabel formTittle;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel nameBooking;
    private javax.swing.JLabel nameEvent;
    private javax.swing.JPanel panelBackground;
    public javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables


    /* Métodos Hover */
    private void btnHoverOn(javax.swing.JButton btn) {
        btn.setBackground(colRed);
        btn.setForeground(colBlack);
    }

    private void btnHoverOut(javax.swing.JButton btn) {
        btn.setBackground(colBlack);
        btn.setForeground(colWhite);
    }

    /* Clase interna para poner img background al JPanel*/
    class BackgroundPanel extends JPanel {

        private Image imgBg;

        @Override
        public void paint(Graphics g) {
            imgBg = new ImageIcon(getClass().getResource("../resources/img-bg-left-dark.jpg")).getImage();
            g.drawImage(imgBg, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
